Step4
next-step/jwp-framework pull request #124
Opened 2020-06-25 06:06 UTC by kjs4395

안녕하세요 리뷰어님!

step4 를 진행하는데 reflection을 사용하며 하려다 보니까 헤매는 부분이 많아 시간이 오래 걸렸습니다!ㅜㅜ
제 나름대로 요구사항을 이해하면서 진행해보려고 했는데 아직도 부족한점이 많은거 같습니다.

리뷰부탁드리겠습니다.
감사합니다!

2020-06-25 17:30 UTC, javajigi requested changes
MVC 구현의 4단계 난이도가 가장 높은데 구현하느라 수고했네요. 👍 
힘들게 구현한 프레임워크를 프로덕션 코드에도 적용해 보면 더 좋을 것 같아요.
피드백 남겼으니 반영해 보세요. 피드백 중 다소 이해가 되지 않는 피드백이 있을 수 있는데요.
부담없이 질문 주세요.

2020-06-25 17:30 UTC, javajigi commented on src/main/java/core/mvc/tobe/PrimitiveTypeUtil.java
> +    public static Object castPrimitiveType(Class<?> clazz, String value) {
이 메소드의 경우 자바의 다형성과 collection을 사용해 if문 제거해 보는 것은 어떨까?

2020-06-25 17:30 UTC, javajigi commented on src/main/java/core/mvc/tobe/helper/ObjectParameterHelper.java
> +    public Object bindingProcess(ParameterInfo parameterInfo, HttpServletRequest request) {
메소드의 복잡도가 높다.
메소드가 한가지 작업만 처리하도록 리팩토링한다.

2020-06-25 17:30 UTC, javajigi commented on src/main/java/core/mvc/tobe/PathPatternUtil.java
> +public class PathPatternUtil {
이 클래스에 대한 단위 테스트 코드 구현해 보는 것은 어떨까?

2020-06-25 17:30 UTC, javajigi commented on src/test/java/core/mvc/tobe/AnnotationHandlerMappingTest.java
> +    }
통합 테스트를 통해 검증한 것은 👍 
단, 좀 더 작은 단위의 단위 테스트를 기반으로 구현하는 연습을 하는 것은 어떨까?

2020-06-25 17:30 UTC, javajigi commented on src/test/java/core/mvc/tobe/AnnotationHandlerMappingTest.java
>  public class AnnotationHandlerMappingTest {
테스트를 통해 검증만 하고 Controller에 적용한 부분은 없다.
Controller 메소드의 인자가 잘 매핑되는지 Controller에도 적용해 검증해 봐야하지 않을까?

2020-06-25 17:30 UTC, javajigi commented on src/main/java/core/mvc/tobe/helper/Helpers.java
> +    }
전체적으로 static으로 구현하는 경향이 있다.
이와 같이 static으로 구현할 경우 테스트가 쉽지 않을 가능성이 높아진다. 
즉, 유연성이 떨어질 가능성이 높다.
static을 사용하기 보다 Helpers를 Dependency Injection 기반으로 구현해 보는 것은 어떨까?
Spring이 DI를 기반으로 하고 있듯이 프레임워크 구현 또한 DI 기반으로 구현하는 것이 가능하다.

2020-06-25 17:30 UTC, javajigi commented on src/main/java/core/mvc/tobe/helper/Helpers.java
> +public class Helpers {
클래스 이름이 의도를 잘 드러내지 않는 것 같다.
더 적합한 이름을 찾아보는 것은 어떨까?

2020-06-25 17:30 UTC, javajigi commented on src/main/java/core/mvc/tobe/ParameterInfo.java
> +    public ParameterInfo(Class<?> type, String name, PathPattern pathPattern, Annotation[] annotations) {
Method에서 모든 값을 꺼낸 후 구현하니까 생성자에 전달할 인자 갯수가 많다.
`ParameterInfo(Method method, int parameterIndex)`와 같이 구현해 보는 것은 어떨까?

2020-07-21 06:05 UTC, kjs4395 commented
안녕하세요 리뷰어님!

저번에 수정하고 나서 요청을 드린다는게 지금까지 요청을 못드리고 있었네요 ㅠㅠ
다시 한번 보면서 더 수정,추가할것 있는거 확인하고 작업하고 요청드려봅니다!

너무 오래끌어서 죄송합니다..ㅜㅜ
그럼 리뷰 조심스럽게 부탁드립니다!

2020-07-21 08:20 UTC, javajigi approved these changes
교육 마지막까지 포기하지 않고 피드백 반영 잘 했네요. 💯 
특히 4단계 미션이 힘든 과제였는데요. 리팩토링하느라 수고했어요.
이번 미션이 Spring의 HandlerMethodArgumentResolver를 이해하는데 도움이 되었기를 바래요.

2020-07-21 08:20 UTC, merged