2단계 - @MVC 구현
next-step/jwp-framework pull request #154
Opened 2020-08-25 16:03 UTC by jinwoo0607

안녕하세요 오랜만인 것 같습니다.
새로 프로젝트 하다가 강의 듣기만 하고 복습을 못했는데 
요새 회사에서 자바로 개발 하고 싶은데 이상하게 파이썬 장고로 서버를 짜라고 차출 당해서
자바를 공부하고 싶은 기념으로 다시 돌아오게 되었습니다
나태했던 자기 자신을 되돌아보고 최소한 DI까지 마무리 하는 것으로 하고 다시 시작해보겠습니다
부족한 부분은 아낌없이 지적 부탁드리고 열심히 해보겠습니다!!

2020-08-25 23:54 UTC, javajigi requested changes
@MVC 구현 잘 했네요. 👍 

단, 프레임워크 구현만 했지 애플리케이션에 적용하지는 않았는데요.
프레임워크를 개선하고 구현하는 목적이 응용 애플리케이션 개발을 위함인 만큼 잘 구현됐는지 반드시 확인하는 습관을 들이면 좋겠어요.
피드백에도 남겼으니 기존 mvc로 구현되어 있던 Controller를 새롭게 구현한 @MVC 기반으로 동작하도록 하면 좋겠네요.

2020-08-25 23:54 UTC, javajigi commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +        }
프레임워크를 구현하는 관점에서 봤을 때 Servlet, Struts1, Struts2와 같은 다양한 프레임워크와의 통합을 하고 싶다.
이와 같이 새로운 기술에 대한 통합을 시도할 경우 if/else가 계속해서 추가될 수 있다.
이와 같이 if/else가 늘어날 것으로 예상되는 부분에 자바의 다형성을 활용해 interface를 추가하고 확장 가능한 구조로 개선해 보면 어떨까?

```java
public interface HandlerAdapter {
    boolean supports(Object handler);

    ModelAndView handle(
        HttpServletRequest request, 
        HttpServletResponse response, 
        Object handler) throws Exception;
}
```

2020-08-25 23:54 UTC, javajigi commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +        requestMappingList.add(ahm);
DispatcherServlet은 서블릿 컨테이너가 생성하고 초기화를 담당한다.
따라서 DI를 통해 LegacyRequestMapping, AnnotationHandlerMapping에 대한 의존관계를 구현하기 힘들다.
이와 같이 DI를 통해 의존관계를 연결하기 힘든 구조의 경우 어떤 구조로 구현하면  LegacyRequestMapping, AnnotationHandlerMapping에 대한 의존 관계를 분리할 수 있을까?

2020-08-25 23:54 UTC, javajigi commented on src/main/java/core/mvc/tobe/ControllerScanner.java
> +                .forEach(method -> {
forEach대신 map으로 구현하는 것은 어떨까?

2020-08-25 23:54 UTC, javajigi commented on src/main/java/core/mvc/asis/DispatcherServlet.java
>  public class DispatcherServlet extends HttpServlet {
기존 MVC에서 애노테이션 기반(@MVC)와 병행해서 동작하도록 구현했다.
기존 Controller를 새롭게 구현한 @MVC와 병행해서 동작하는지 확인하기 위해 기존 Controller의 일부를 @MVC 기반 Controller로 수정한다.
이와 같이 이동해 봄으로써 asis MVC 프레임워크와 새롭게 구현한 tobe MVC 프레임워크가 동시에 동작하도록 구현해 본다.

2020-08-29 12:53 UTC, jinwoo0607 commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +        }
조언 정말 감사합니다 적용해보겠습니다!

2022-08-15 01:34 UTC, closed without merging