[2단계 - @MVC 구현] 리뷰 요청드립니다.
next-step/jwp-framework pull request #175
Opened 2022-07-31 09:16 UTC by seondongpyo

안녕하세요, 현구님. 2단계 미션 작성해봤습니다.
기존의 MVC 프레임워크와 더불어, 새로 구현한 애노테이션 기반의 MVC 프레임워크를 처리할 수 있도록 적용해봤습니다.
기존 Controller 인터페이스를 구현했던 핸들러들을 실제로 애노테이션 기반의 핸들러로 변경하는 작업은
2단계와 3단계 중 어느 단계에서 해야할지 여전히 고민이지만 일단은 `DispatcherServlet`에만 적용해봤습니다.
혹 2단계에서 기존 핸들러들을 새로운 MVC 프레임워크 핸들러로 전환해도 상관없다면 같이 진행해보겠습니다.
이번 리뷰도 잘 부탁드리고, 남은 주말도 즐거운 시간 되시길 바랍니다. 감사합니다 🙇

2022-08-02 01:58 UTC, kang-hyungu requested changes
선동님 2단계 미션도 빠르게 잘 구현해주셨네요.
기존 Controller 인터페이스를 구현했던 핸들러들을 실제로 애노테이션 기반의 핸들러로 변경하는 작업은 3단계에서 진행해보시기 바랍니다.
2단계 미션은 인터페이스 기반 컨트롤러와 애노테이션 기반 컨트롤러가 공존하도록 작업해보시기 바랍니다.
관련하여 몇 가지 피드백 남겼으니 참고해서 수정해보세요.

2022-08-02 01:58 UTC, kang-hyungu commented on src/main/java/core/mvc/asis/LegacyHandlerMapping.java
>      private static final Logger logger = LoggerFactory.getLogger(DispatcherServlet.class);
로거 설정 확인이 필요해보이네요

2022-08-02 01:58 UTC, kang-hyungu commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +        legacyHandlerMapping.initMapping();
LegacyHandlerMapping와 AnnotationHandlerMapping 객체를 생성하고 초기화하는 과정에서 비슷한 패턴이 보이네요.
새로운 HandlerMapping 구현체가 등장하더라도 DispatcherServlet 클래스가 수정되지 않도록 만들어보아요.

1. HandlerMapping 인터페이스에 initialize라는 초기화 메서드를 추가해보아요.
2. handlerMappings을 일급 컬렉션으로 만들고 HandlerMapping의 전체 구현체를 initialize 메서드로 초기화하는 작업을 추가해보시기 바랍니다.
3.  DispatcherServlet 클래스에 있는 `Optional<Object> getHandler(HttpServletRequest request)` 메서드를 옮겨보시기 바랍니다.

2022-08-02 01:58 UTC, kang-hyungu commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +        if (handler instanceof Controller) {
DispatcherServlet에서 인터페이스 기반 컨트롤러를 사용할지 어노테이션 기반 컨트롤러를 사용할지 결정하는 로직이 있네요.
어댑터 패턴을 사용해서 인터페이스 기반 컨트롤러와 어노테이션 기반 컨트롤러를 통합해보면 어떨까요?

```java
public interface HandlerAdapter {
    boolean supports(Object handler);

    ModelAndView handle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception;
}
```

```java
public class HandlerExecutionHandlerAdapter implements HandlerAdapter {
    @Override
    public boolean supports(Object handler) {
        // todo
    }

    @Override
    public ModelAndView handle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
        // todo
    }
}
```

```java
public class ControllerHandlerAdapter implements HandlerAdapter {
    @Override
    public boolean supports(Object handler) {
        // todo
    }

    @Override
    public ModelAndView handle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
        // todo
    }
}
```

2022-08-03 00:47 UTC, kang-hyungu approved these changes
선동님 피드백 반영 잘 해주셨습니다.
추가로 남긴 코멘트는 다음 단계 진행하면서 적용해보시기 바랍니다.

2022-08-03 00:47 UTC, kang-hyungu commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +        mav.getView().render(mav.getModel(), request, response);
```suggestion
        mav.render(mav.getModel(), request, response);
```

view를 꺼내서 렌더링하기 보다 ModelAndView에 메서드를 추가해보면 어떨까요

2022-08-03 00:47 UTC, kang-hyungu commented on src/main/java/core/mvc/tobe/HandlerAdapters.java
> +        initHandlerAdapters();
initHandlerAdapters 메서드를 따로 추출할 필요가 있을까요?

2022-08-03 00:47 UTC, kang-hyungu commented on src/main/java/core/mvc/tobe/HandlerAdapters.java
> +        Reflections reflections = new Reflections("core.mvc.tobe");
패키지를 인자로 넘겨받도록 만들어야 좀더 유연한 구조가 되겠네요.

2022-08-03 00:47 UTC, kang-hyungu commented on src/main/java/core/mvc/tobe/HandlerMappings.java
> +    public HandlerMappings() {
HandlerAdapters와 마찬가지로 수정해보시기 바랍니다.

2022-08-03 00:47 UTC, merged

2022-08-03 02:29 UTC, seondongpyo commented on src/main/java/core/mvc/tobe/HandlerAdapters.java
> +        initHandlerAdapters();
개인적으로 생성자에 많은 코드가 작성되는 걸 선호하지 않아서 메서드로 분리했습니다.