Step2 리뷰 요청드립니다.
next-step/jwp-framework pull request #18
Opened 2019-08-09 17:17 UTC by circlee

step2 의 요구사항을 잘 이해 못한듯 싶네요.
피드백 기다리겠습니다.
감사합니다.!

요구사항1. AnnotationHandlerMappingTest의 TestCase 가 돌아가도록 작성하였습니다.
요구사항2.DispatcherServlet 내 service를 분기 하였습니다.

2019-08-10 06:34 UTC, byjo requested changes
구현해야하는 요구사항은 잘 수행하셨습니다. 👍

다만 AnnotationHandlerMappingTest에 handler를 실행하는 테스트는 없는지라, 
이를 보완하기 위해 handler를 잘 실행하고 있는지도 테스트 해보면 더 좋을 것 같습니다. 
(TestUserController가 테스트에 사용하기 적당해 보이네요)

그리고 요구사항2가 잘 적용 되었는지 확인하기 위해, 일부 Controller는 어노테이션 기반으로 동작하도록 변경하여 잘 동작하는지를 보면 더 좋을 것 같아요.

혹시나 이해가 안가거나 문의사항이 있으시다면, 깃헙 멘션이나 슬랙 DM 주세요.

2019-08-10 06:34 UTC, byjo commented on src/main/java/core/mvc/tobe/HandlerExecution.java
> +        return (ModelAndView) this.invokeMethod.invoke(this.invokeInstance, new Object[]{request, response});
Method의 invoke 메서드를 보면 `invoke(Object obj, Object... args)` 로 나와있죠.
`Object...` 은 가변 인자로 배열이 자동으로 생성되기 때문에, 굳이 새로운 배열을 만들어주지 않아도 되어요.

함께 보면 좋을 자료 첨부드리니, 참고하시면 좋을 것 같아요.
[Java Doc - Varargs](https://docs.oracle.com/javase/8/docs/technotes/guides/language/varargs.html)
[Effective Java - Item.42 varargs는 신중히 사용하라](https://duzi077.tistory.com/242)

2019-08-10 06:34 UTC, byjo commented on src/main/java/core/mvc/tobe/HandlerExecution.java
> +    public Object getInvokeInstance() {
제 생각에 HandlerExecution을 사용하는 외부에서는
어떤 기술(reflection의 method invoke 사용)로 동작하는지 몰라도 되니 메서드 명의 `invoke` 는 불필요하지 않을까 싶은데, 
어떻게 생각 하시나요?

2019-08-10 06:34 UTC, byjo commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +            basePackageInitialize(basePackage);
해당 수정사항은 엄밀히 보자면 요구사항 1보다는 요구사항 2에 맞는 내용이겠죠?
앞으로는 git rebase를 사용해서 이전 커밋을 수정해서, 의미있는 커밋 로그를 만들어보는 건 어떨까요?

[Git 도구 - 히스토리 단장하기](https://git-scm.com/book/ko/v1/Git-%EB%8F%84%EA%B5%AC-%ED%9E%88%EC%8A%A4%ED%86%A0%EB%A6%AC-%EB%8B%A8%EC%9E%A5%ED%95%98%EA%B8%B0)

2019-08-10 06:34 UTC, byjo commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +            ModelAndView modelAndView = handlerExecution.handle(req, resp);
여기서 요청 처리가 끝나면, 사용자가 정상적인 응답을 받을 수 있을까요?

2019-08-10 06:34 UTC, byjo commented on src/main/java/core/exceptions/AnnotationHandlerMappingException.java
> +public class AnnotationHandlerMappingException extends RuntimeException {
custom exception 생성 좋네요 👍

2019-08-10 06:34 UTC, byjo commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +            Set<HandlerExecution> handlerExecutions = getHandlerExecurions(controllerClasses);
오타가 있네요.

2019-08-10 06:34 UTC, byjo commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +        if (base instanceof String) {
혹시 Reflection 생성자의 내부나 document를 확인 해보셨을까요?
reflection의 ConfigurationBuilder가 해주는 일이기 때문에 불필요한 메소드로 보입니다.

[Java Doc - Reflections](https://static.javadoc.io/org.reflections/reflections/0.9.10/org/reflections/Reflections.html#Reflections-java.lang.Object...-)

2019-08-10 06:34 UTC, byjo commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +    private void putHandlerExecution(HandlerKey handlerKey, HandlerExecution handlerExecution) {
굳이 별개의 메서드로 분리한 이유가 있을까요? 
제 생각에는 `putHandlerExecutions()` 외에는 호출할 곳이 보이지 않는데, 비슷한 이름의 메서드가 또 있으니 흐름 파악에 방해가 되는 것 같아요.

2019-08-10 06:34 UTC, byjo commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +        return Optional.ofNullable(controllerClasses)
스트림을 사용하는 것은 좋지만 지금과 같은 경우 AnnotationHandlerMapping 내 있는 대부분의 private 메서드에서 순회가 발생하고 있어요.

지금의 코드가 `initialize()` 에서 수행하는 아래 사항들을 쉽게 나타내고 있을까요?
1. 특정 Annotaion이 있는 클래스 set을 순회하며
2. 특정 Annotaion이 있는 메서드를 찾아
3. key, value에 맞게 map에 추가한다.

반복과 분기를 지양하는 것은 많지만 코드 가독성을 위해선 필요할 때도 있다고 생각해요.
[Effective Java 3E - Ch.7 람다와 스트림](https://sheerheart.tistory.com/entry/Effective-Java-3E-7%EC%9E%A5-%EB%9E%8C%EB%8B%A4%EC%99%80-%EC%8A%A4%ED%8A%B8%EB%A6%BC-%EC%9A%94%EC%95%BD%EC%A0%95%EB%A6%AC)의 아이템 45도 한 번 읽어보시면 좋을 것 같아요.

2019-08-12 12:34 UTC, byjo requested changes
요구사항 구현이 반영되지 않은 부분이 있어 수정 요청 드립니다.
드린 코멘트의 내용은 3단계 리팩토링 과정에서 함께 반영하면 좋은 내용이니,
요구사항 우선으로 반영 부탁드려요. 👏

2019-08-12 12:34 UTC, byjo commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +        if (handlerExecution != null) {
만약 새로운 방식의 mapping 방법이 추가되면 service 메서드에 else if문이 추가되어야 할까요? 
xxxService라는 새로운 메서드도 생기게 되구요. 이는 OCP에 어긋나는 것 같습니다. 
그리고 `xxxService()` 메서드에는 동일한 형태의 try-catch 문으로 중복이 있네요.

동일한 역할을 하는 객체(RequestMapping, AnnotationHandlerMapping)를 추상화한 인터페이스를 구현 하고,
이러한 구현체들이 계속 추가 되더라도 DispatcherServlet에는 큰 변화가 없도록 해보는건 어떨까요?
3단계에서는 이러한 방식으로 확장 가능한 프레임워크로 만드신다면 좋겠습니다.

2019-08-12 12:34 UTC, byjo commented on src/test/java/core/mvc/tobe/AnnotationHandlerMappingTest.java
> +    @DisplayName("handler 호출 테스트 : return model 비교")
👍

2019-08-12 12:34 UTC, byjo commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +			basePackageInitialize(basePackage);
현재 구조에서 'initialize() 에서 무슨 일을 하지?' 하고 살펴보게 되면, 호출하는 함수를 따라 이리저리 움직이게 되는데요.

클린 코드에서 클래스 내 코드의 순서에 대한 이야기(적절한 행 길이를 유지하라)가 있는데, 
참고하셔서 이 클래스의 코드 가독성을 높이는 것이 필요해 보입니다.
[클린 코드 - Ch 03. 형식 맞추기](https://github.com/Yooii-Studios/Clean-Code/blob/master/Chapter%2005%20-%20%ED%98%95%EC%8B%9D%20%EB%A7%9E%EC%B6%94%EA%B8%B0.md)

2019-08-12 12:34 UTC, byjo commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +		for (Object base : bases) {
Reflection 생성자는 가변인자를 받기 때문에 for문 순회를 하지 않아도 됩니다. 
[Java Doc - Reflections](https://static.javadoc.io/org.reflections/reflections/0.9.10/org/reflections/Reflections.html#Reflections-java.lang.Object...-)

2019-08-12 12:34 UTC, byjo commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +import static java.util.Collections.emptySet;
사용 안하는 import문은 제거하는게 추후 코드 관리에 좋겠죠?

2019-08-12 12:36 UTC, byjo commented
누락된 요구사항 전달 드립니다.

1. 요구사항 1에 있는 내용이 구현 되어있지 않습니다.
> @RequestMapping()에 method 설정이 되어 있지 않으면 모든 HTTP method를 지원해야 한다.

2. 요구사항 2에 있는 내용(및 피드백으로 전달 드린 내용)이 구현되어 있지 않습니다. 
> 즉, 지금까지 사용한 MVC 프레임워크와 새롭게 구현한 애노테이션 기반 MVC 프레임워크가 공존해야 한다.

>그리고 요구사항2가 잘 적용 되었는지 확인하기 위해, 일부 Controller는 어노테이션 기반으로 동작하도록 변경하여 잘 동작하는지를 보면 더 좋을 것 같아요.

위 두 사항 먼저 반영해주시고, 위에 드린 코멘트들은 3단계에 함께 적용하시면 좋을 것 같습니다.

2019-08-12 16:31 UTC, circlee commented
실수로 branch 삭제해버렸네요.
restore 하여 리뷰요청 드립니다.
감사합니다.

2019-08-13 04:14 UTC, byjo approved these changes
수정해주신 부분 확인했습니다. 
두 프레임워크의 공존을 확인하는 테스트 코드도 잘 작성 하셨네요. 👏

다만, 이를 적용하면서 레거시 MVC 기반의 코드에 대한 수정도 발생하였는데요. 
레거시 MVC 기반에 대한 변경 사항은 원복하고, 
피드백 드린 내용과 3단계 힌트를 참고해 리팩토링을 진행하시면 좋을 것 같습니다.

도움이 필요하신 내용이 있으면 깃헙 멘션이나 슬랙 DM 주시구요. 다음 단계도 화이팅입니다!

2019-08-13 04:14 UTC, byjo commented on src/main/java/core/mvc/asis/Controller.java
> +public interface Controller extends ModelAndViewHandler {
새로운 방식의 MVC 프레임워크가 생기면서 Controller interface 수정이 발생했는데요.
기존에 잘 돌아가는 부분까지 변경사항이 생긴건데, 만약 이 프로젝트가 실 서비스중인 프로젝트라면 안정성을 보장할 수 있을까요?

우리의 목표는 점진적인 개선이니 기존 코드는 유지하는 것이 좋아 보입니다.

2019-08-13 04:14 UTC, byjo commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +                .filter(Objects::nonNull)
필요한 filter일까요?

2019-08-13 04:14 UTC, byjo commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +        if (modelAndView == null) {
DispatcherServlet에서 null 체크를 하는 것 보다, 
handler가 유효한 ModelAndView return을 보장하는 것이 더 좋을 것 같습니다.

2019-08-13 04:14 UTC, byjo commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +        if (handler instanceof ModelAndViewHandler) {
지금은 기존의 Controller Interface를 수정해서 handler들이 모두 ModelAndViewHandler의 구현체인 상태인데요.

레거시 MVC 기반의 코드를 그대로 유지한다 가정했을 때, handler의 타입이 Controller나 HandlerExecution이 되겠죠.
두 handler는 실행 방식과 그 return 값이 다르기 때문에 `executeHandler()` 메서드 안에서는 if/else 문이 생기게 되고, 이는 OCP에 어긋나게 됩니다.

3단계에서는 handler를 실행하고 ModelAndView를 return으로 받는 부분을 추상화 해보면 좋을 것 같아요. 
```
public interface HandlerAdapter {
    boolean supports(Object handler);

    ModelAndView handle(
        HttpServletRequest request, 
        HttpServletResponse response, 
        Object handler) throws Exception;
}
```

2019-08-13 04:15 UTC, merged