Step4: Controller 메소드 인자 매핑
next-step/jwp-framework pull request #201
Opened 2022-08-10 02:08 UTC by ghojeong

개인적인 색깔을 넣기 보다는,
미션 요구사항과 Spring 구조에 집중할 수 있도록 구현해보았습니다.
jwp-jdbc 에 이미 구현되어 있는 구조를 최대한 참고하게 되었습니다.

2022-08-10 17:25 UTC, yongdae requested changes
이전 단계에 의견드린 부분을 포함해 멋지게 4단계 미션을 완수해주셨네요. 💯 
검증 뿐만 아니라 설계를 잘 해주셔서 다시 한번 더 고민하고 배울 수 있었습니다.

소소하지만 한가지 의견을 드린 부분이 있으니 확인 후 리뷰 요청 부탁드릴께요!

2022-08-10 17:25 UTC, yongdae commented on src/test/java/core/mvc/resolver/RequestParamArgumentResolverTest.java
> +class RequestParamArgumentResolverTest {
인자를 자동으로 맵핑해주는 기능에 대한 테스트를 상세하게 만들어주셨네요.
케이스를 요구사항에 따라 정의해주셔서 잘 정리해주셔서 쉽게 이해 할 수 있었습니다. 💯

2022-08-10 17:25 UTC, yongdae commented on src/test/java/core/mvc/resolver/PathVariableArgumentResolverTest.java
> +class PathVariableArgumentResolverTest {
👍

2022-08-10 17:25 UTC, yongdae commented on src/main/java/core/mvc/resolver/MethodParameter.java
> +    }
이 메서드는 PathVariableArgumentResolver, RequestParamArgumentResolver만 사용하는 부분이니
MethodParameter 대신 PathVariableArgumentResolver, RequestParamArgumentResolver가 가질 수 있게 구조를 변경해보면 좋을 것 같은데 어떻게 생각하시나요? 🤔

2022-08-12 13:54 UTC, ghojeong commented on src/main/java/core/mvc/resolver/MethodParameter.java
> +    }
어떻게 할지 고민하다가, PathVariableArgumentResolver, RequestParamArgumentResolver 의 공통 로직을 가지는
추상 클래스인 AbstractAnnotationArgumentResolver 를 선언하도록 했습니다.

HttpRequestArgumentResolver 와 HttpResponseArgumentResolver 에서는,
MethodParameter 의 위 로직이 사용되지 않으므로, 적절한 피드백 같습니다.

2022-08-13 00:11 UTC, yongdae approved these changes
의견드린 부분을 멋지게 반영해주셨네요. 💯 
다음 단계로 넘어가도록 하겠습니다. 

아 그리고 교정 수술 받으신 눈도 잘 회복되시면 좋겠네요.
수고하셨습니다. 🙇

2022-08-13 00:11 UTC, yongdae commented on src/main/java/core/mvc/resolver/AbstractAnnotationArgumentResolver.java
> +public abstract class AbstractAnnotationArgumentResolver implements ArgumentResolver {
의견드린 부분을 반영해주셨네요. 👍

2022-08-13 00:11 UTC, merged