2단계 - @MVC 구현
next-step/jwp-framework pull request #214
Opened 2022-08-14 15:50 UTC by jsyang-dev

안녕하세요~ 정완님!
2번째 미션 리뷰 요청드립니다.

ServletFilter를 사용해서 구현해봤는데, 미션의 의도와  맞을지 궁금하네요.
그리고 미션 내용중에 "@RequestMapping()에 method 설정이 되어 있지 않으면 모든 HTTP method를 지원해야 한다." 라는 부분이 있는데, 정확한 의도가 궁금합니다. method 설정이 되지 않은 것과 GET이 둘다 존재하면 어떤 녀석이 해당 요청을 처리해야 하는 걸까요?

그럼 이번 미션도 잘 부탁드립니다. 🙏

2022-08-15 09:59 UTC, ghojeong commented
> "@RequestMapping()에 method 설정이 되어 있지 않으면 모든 HTTP method를 지원해야 한다." 라는 부분이 있는데, 정확한 의도가 궁금합니다. method 설정이 되지 않은 것과 GET이 둘다 존재하면 어떤 녀석이 해당 요청을 처리해야 하는 걸까요?

HTTP Method 가 명시되어 있지 않으면 GET, POST, PUT, DELETE, PATCH 등등을 포함한 모든 [HTTP Method](https://developer.mozilla.org/ko/docs/Web/HTTP/Methods) 를 지원해야한다는 의미입니다.

만약 명시되지 않은 것 과 GET 이 둘다 존재한다면,
GET 요청이 들어왔을 때는 GET 으로 요청을 처리하고,
POST, PUT 등이 들어왔을 때는 설정되지 않은 쪽으로 요청을 처리하면 됩니다.

2022-08-15 10:18 UTC, ghojeong requested changes
양정수님!
2단계 MVC 구현 미션을 의도와 다르게 이해하신듯 하여 수정 요청드립니다.
구현해야하는 내용은 MVC "프레임워크" 이지, ServletFilter 가 아닙니다.

기존의 `core.mvc.asis` 의 프레임워크 코드를 활용하여 `next.controller` 들이 구현되어 있는데,
`core.mvc.tobe` 에 새로 프레임워크를 구현하여, `next.controller` 를 리팩토링해야합니다.
주로 미션을 진행해야하는 패키지는 `core.mvc`라고 생각해주시면 좋을 것 같습니다.

최종적으로는  `core.mvc.asis` 에 있는 코드를 모두 지우더라도,
모든 기능이 정상적으로 돌아가는 리팩토링 경험을 해보셨으면 좋겠습니다.

2022-08-15 10:18 UTC, ghojeong commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +    private final Map<HandlerKey, HandlerExecution> handlerExecutions = Maps.newHashMap();
내부 맴버를 final 로 설정해주시는 점 좋습니다. 👍

2022-08-15 10:18 UTC, ghojeong commented on src/main/java/core/web/filter/AnnotationHandlerMappingFilter.java
> +    private AnnotationHandlerMapping annotationHandlerMapping;
> ServletFilter를 사용해서 구현해봤는데, 미션의 의도와 맞을지 궁금하네요.

미션의 의도와 다른 것 같습니다.
미션에서 요구한 것은 MVC "프레임워크" 를 구현하는 것이지,
"필터"를 구현해서 적용하는 것과는 다르다고 생각합니다.

ServletFilter 를 적용하려 하기 보다는,
DispatcherServlet 과 RequestMapping 을 리팩토링하는게 미션에서 요구하는 내용입니다.

2022-08-15 10:18 UTC, ghojeong commented on src/main/java/next/controller/tobe/TestController.java
> +}
현재 기존 controller 에 대한 리팩토링 없이,
TestController 만 추가를 한것 같은데, next.controller 안에 있는 Controller 들을 모두 리팩토링할 수 있는 방향으로 미션을 진행해주시면 좋을 것 같습니다.

2022-08-17 08:30 UTC, jsyang-dev commented
정완님~ 미션의 의도에 맞게 수정해보았습니다.
리뷰 부탁드립니다!

2022-08-17 15:31 UTC, ghojeong approved these changes
양정수님!
2단계의 미션 요구사항을 매우 훌륭하게 구현해주셨습니다. 👍 
다음 단계를 진행하기에 충분하다고 생각되어 빠르게 머지하겠습니다.

2022-08-17 15:31 UTC, ghojeong commented on src/main/java/core/mvc/asis/RequestMapping.java
> +//        mappings.put("/users/update", new UpdateUserController());
요구사항을 훌륭하게 구현해주셔서,
RequestMapping 에 있던 부분을 주석처리할 수 있게 되었군요. 👍

2022-08-17 15:31 UTC, ghojeong commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
>      }
reflection 을 통해서, 어노테이션과 Method 를 훌륭하게 잘 읽어오시네요 👍

2022-08-17 15:31 UTC, ghojeong commented on src/main/java/next/controller/ListUserController.java
> +    public ModelAndView list(HttpServletRequest request, HttpServletResponse response) throws Exception {
RequestMapping 어노테이션을 활용해 컨트롤러 또한 매우 훌륭하게 리팩토링해주셨습니다. 👍

2022-08-17 15:31 UTC, merged