🚀 4단계 - Controller 메소드 인자 매핑
next-step/jwp-framework pull request #253
Opened 2022-08-30 15:11 UTC by hongbin-dev

안녕하세요 구구!
피드백 반영과 MVC에서 파라미터를 매핑하는 미션을 구현해봤습니다..!

2022-08-30 15:15 UTC, hongbin-dev commented on src/main/java/core/mvc/tobe/HandlerMappings.java
> +    }
https://github.com/next-step/jwp-mvc/pull/233#discussion_r956975419

아이디어가 되게 좋은 것 같아요!! 코드리뷰 반영해봤습니다..!
또 외부에서 handlerMappings를 외부에서 주입받도록 변경해봤습니다.

2022-08-30 15:15 UTC, hongbin-dev commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +    }
https://github.com/next-step/jwp-mvc/pull/233#discussion_r956976492

일급컬렉션을 분리해봤습니다. 관련코드가 확실히 깔끔해졌네요 🙂
자주 잊고있는데, '책임이 큰 객체들은 새로운객체로 포장하면 좋겠다' 생각하고 있으면 좋을 것 같아요

2022-09-01 03:44 UTC, kang-hyungu requested changes
홍빈님 몇 가지 피드백 남겼습니다.
수정해보시고 리뷰 재요청 주세요~!

2022-09-01 03:44 UTC, kang-hyungu commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +    public DispatcherServlet(HandlerMappings handlerMappings, HandlerAdapters adapters) {
서블릿을 구현한 것이니 생성자보다 init 메서드에서 handlerMappings, adapters를 초기화하는게 어떨까요?

2022-09-01 03:44 UTC, kang-hyungu commented on src/main/java/core/mvc/tobe/utils/ParameterSupport.java
> +public interface ParameterSupport {
인터페이스로 만든 이유가 있을까요?

2022-09-01 03:44 UTC, kang-hyungu commented on src/main/java/core/mvc/tobe/HandlerExecution.java
> +        for (int i = 0; i < parameterNames.length; i++) {
for문이 2중 for문이라 약간 복잡해보이네요
메서드 추출해서 읽기 좋게 바꿔보는게 어떨까요?

2022-09-01 03:44 UTC, kang-hyungu commented on src/main/java/core/mvc/tobe/utils/TypeUtils.java
> +public interface TypeUtils {
이 클래스도 인터페이스로 만든 이유가 있을까요?

2022-09-01 03:44 UTC, kang-hyungu commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +    public DispatcherServlet(HandlerMappings handlerMappings, HandlerAdapters adapters) {
테스트는 정상 동작하는데 서버를 실행시키니 에러가 발생하네요. 정상 실행되도록 확인 부탁드려요~!

2022-09-03 02:50 UTC, hongbin-dev commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +    public DispatcherServlet(HandlerMappings handlerMappings, HandlerAdapters adapters) {
앗.. 테스트만 체크하고, 확인을 못했네요. 반영해봤습니다.

2022-09-03 02:51 UTC, hongbin-dev commented on src/main/java/core/mvc/tobe/utils/ParameterSupport.java
> +public interface ParameterSupport {
List 인터페이스와 비슷하게 생각했는데요.
유틸성 클래스가 인스턴스로 만들어짐을 방지하기 위해서 인터페이스로 정의해봤습니다!

2022-09-03 02:51 UTC, hongbin-dev commented on src/main/java/core/mvc/tobe/HandlerExecution.java
> +        for (int i = 0; i < parameterNames.length; i++) {
resolver 찾는 부분을 메서드로 분리해봤습니다!

2022-09-03 07:39 UTC, kang-hyungu approved these changes
홍빈님 미션 잘 진행해주셨습니다.
pr은 머지 처리할게요 수고하셨습니다.

2022-09-03 07:39 UTC, kang-hyungu commented on src/main/java/core/mvc/tobe/HandlerExecution.java
> +            .mapToObj(idx -> {
이 부분도 메서드로 추출하면 코드가 좀더 깔끔해지겠네요.

2022-09-03 07:39 UTC, kang-hyungu commented on src/main/java/core/mvc/tobe/utils/ParameterSupport.java
> +public interface ParameterSupport {
기본 생성자를 private으로 만들어두면 말씀하신 문제를 방지할 수 있습니다.
인터페이스를 유틸성 클래스로 사용하지 않으니 클래스로 바꾸는걸 추천합니다.

2022-09-03 07:39 UTC, merged