Step4
next-step/jwp-framework pull request #276
Opened 2022-09-18 21:06 UTC by ljh0326

2022-09-19 02:06 UTC, gwonsungjun requested changes
안녕하세요!
4단계 구현 잘 해주셨습니다!
몇가지 피드백 남겨놨는데요. 피드백 반영 후 다시 요청 부탁 드리겠습니다!
애플리케이션 정상 구동 여부도 같이 확인 부탁드려요!
고생하셨습니다 🙇‍♂️

2022-09-19 02:06 UTC, gwonsungjun commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +    private final ArgumentResolverMapping argumentResolverMapping = new ArgumentResolverMapping();
ArgumentResolverMapping 생성 시  basePackage 정보를 전달하지 않아도 되나요~?

2022-09-19 02:06 UTC, gwonsungjun commented on src/main/java/core/mvc/tobe/HandlerExecution.java
> +    Method method;
접근제어자를 default로 선언하신 이유가 따로 있을까요?

2022-09-19 02:06 UTC, gwonsungjun commented on src/main/java/core/di/factory/BeanFactory.java
> +    }
어디에 사용되는 메서드 인가요?

2022-09-19 02:06 UTC, gwonsungjun commented on src/test/java/core/mvc/tobe/HandlerMethodArgumentResolverTest.java
> +    }
해당 테스트는 어떤 의도로 작성하셨나요?
검증이 따로 없는 디버깅 용도의 테스트 코드를 유지가 필요할지 고민 해보시면 좋을 것 같아요 :)

2022-09-19 02:06 UTC, gwonsungjun commented on src/main/java/core/mvc/tobe/util/PathPatternUtil.java
> +public class PathPatternUtil {
해당 클래스를 사용하는 곳이 없어보여요! 제거하면 어떨까요?

2022-09-19 02:06 UTC, gwonsungjun commented on src/main/java/core/mvc/tobe/MethodParameter.java
> +public class MethodParameter {
👍

2022-09-19 02:06 UTC, gwonsungjun commented on src/main/java/core/mvc/tobe/resolver/RequestParamArgumentResolver.java
> +        return result;
RequestParamArgumentResolver는 string 만 지원하나요~?

2022-11-13 18:58 UTC, ljh0326 commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +    private final ArgumentResolverMapping argumentResolverMapping = new ArgumentResolverMapping();
넣어줬습니다!

2022-11-13 18:58 UTC, ljh0326 commented on src/main/java/core/mvc/tobe/HandlerExecution.java
> +    Method method;
으아 놓쳤습니다!

2022-11-13 18:58 UTC, ljh0326 commented on src/main/java/core/di/factory/BeanFactory.java
> +    }
만들당시 필요할꺼다라고 예측해서 만들었는데 안썼네요 ㅜ, 역시 미리 생각하고 만들어둔 코드는 대부분 쓸모없는것 같습니다... 필요할때만 만들기로 :)

2022-11-13 18:58 UTC, ljh0326 commented on src/main/java/core/mvc/tobe/util/PathPatternUtil.java
> +public class PathPatternUtil {
그러네요.. 위와 마찬가지로 ㅜㅜ 미리만든건 안쓰게되네요

2022-11-13 23:26 UTC, javajigi approved these changes
피드백 반영하느라 수고했어요. 👍 
이 미션의 commit log 또한 AOP 미션과 같네요.
무엇인가 절차대로 진행되지 않아 commit log가 꼬이는 것 같아요.
git에 대해 추가학습해 보면 좋을 것 같아요.

2022-11-13 23:27 UTC, merged