4단계 - Controller 메소드 인자 매핑
next-step/jwp-framework pull request #279
Opened 2022-09-21 15:04 UTC by dev-jiwonyang

안녕하세요 리뷰어님!!
2단계에서 이미 3단계 요구사항을 끝내서 4단계로 진행을 바로 했는데 괜찮을까요?!
미리 여쭤본다는 것을 깜빡했네요 ㅠㅠ
리뷰 잘 부탁드립니다 :)

2022-09-21 22:39 UTC, ghojeong commented
> 2단계에서 이미 3단계 요구사항을 끝내서 4단계로 진행을 바로 했는데 괜찮을까요?!

넵 괜찮습니다!

2022-09-22 11:47 UTC, ghojeong requested changes
양지원님!
4단계의 엄청난 퀄리티에 그저 박수를 칠 수밖에 없네요.
엄청난 시간과 고심을 쏟으신게 느껴집니다.

사소한 오타? 같은 부분들을 언급해보았는데,
고쳐주시면 바로 머지하도록 하겠습니다.

2022-09-22 11:47 UTC, ghojeong commented on src/main/java/next/controller/UserController.java
> +        if (!UserSessionUtils.isSameUser(session, user)) {
> Controller 메소드의 인자 타입에 따라 HttpServletRequest에서 값을 꺼내와 자동으로 형 변환

User 타입으로 매우 잘 형변환 되는 것 확인했습니다.
기능 구현 및 리팩토링 잘해주셨네요. 👍

2022-09-22 11:47 UTC, ghojeong commented on src/test/java/core/mvc/resolver/PathVariableArgumentResolverTest.java
> +    }
User 객체에 대한 변환 뿐만 아니라,
TestUserController 의 show_pathvariable 메서드를 통해,
PathVariable 에 관한 요구사항도 매우 잘 동작하는 군요 👍

2022-09-22 11:47 UTC, ghojeong commented on src/main/java/core/mvc/resolver/HandlerMethodArgumentResolverMapping.java
> +                .filter(clazz -> HandlerMethodArgumentResolver.class.isAssignableFrom(clazz))
캬...
Resolver 를 static List 로 하드코딩해서 갖도록 하는 분도 있는데,
"core.mvc.resolver" 를 스캔해서 가져오도록 하는 분은 지원님이 최초인것 같습니다.
굉장히 리플렉션을 멋있게 활용해주셨다고 생각합니다. 👍

2022-09-22 11:47 UTC, ghojeong commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +        argumentResolverMapping.initialize();
어차피 서블릿 객체는 재사용되므로, 굳이 static 으로 하지 않고
이렇게 initialize 하는 것도 충분히 멋진것 같습니다. 👍

2022-09-22 11:47 UTC, ghojeong commented on src/main/java/core/mvc/resolver/HttpServletRequestArgumentResolver.java
> +}
SessionArgumentResolver 가 있음에도,
HttpServletRequestArgumentResolver 를 남겨두신 이유는 하위 호환 때문이라고 이해했습니다.
그렇다면 설령 사용되지 않더라도, HttpServletResponseArgumentResolver 또한 만들어두는게 좋지 않을까 해서 제안해봅니다.

2022-09-22 11:47 UTC, ghojeong commented on src/test/java/core/mvc/resolver/PrimitiveTypeArgumentResolverTest.java
> +        methodParameters.forEach(methodParameter -> assertEquals(true, resolver.supportsParameter(methodParameter)));
여러개의 assert 를 할 때는 SoftAssertions 를 해보는 것은 어떨까 제안을 해봅니다.
지금도 충분히 좋아서 꼭 적용하지 않으셔도 괜찮습니다.

2022-09-22 11:47 UTC, ghojeong commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +import java.lang.reflect.Method;
이 Method 에 대한 import 는 어디에 쓰이고 있나요?

2022-09-22 11:47 UTC, ghojeong commented on src/main/java/core/mvc/resolver/PrimitiveType.java
> +    private final Function<String, Object> parser;
솔직히 코드를 읽으면서 제일 인상깊었던게, 바로 이 enum PrimitiveType 입니다.
primitiveType 과 wrapperType 을 분리해서 생각하신것도 대단하고,
isPrimitive 와 convert 관련 로직을 enum 안에 넣으신 것도 대단하다고 생각이 드네요.

단순히 PrimitiveTypeArgumentResolver 뿐만 아니라 다른 Resolver 들에게도 사용되고 있어서,
굉장히 재사용성이 높은 코드라고 생각합니다. 👍 
읽다가 박수를 치고 싶어서 언급을 해보았습니다. 👏

2022-09-22 11:47 UTC, ghojeong commented on src/main/java/core/mvc/resolver/ModelAttributeArgumentResolver.java
> +    }
특히 ModelAttribute 의 constructor 를 생성할 때,
PrimitiveType.convert 를 사용하는 부분 엄청나다고 생각했습니다.

Controller 부분의 MethodParameter 뿐만 아니라 더 모델의 생성자에게도,
PrimitiveType 의 로직을 재사용하는 부분은 "진짜 와 잘 짰다" 라는 감탄을 하게 되더라고요.

2022-09-30 02:11 UTC, ghojeong approved these changes
양지원님!
피드백을 드린 지 시간이 지났는데,
머지를 해도 충분한 상태에서 굳이 시간을 끄는 것은 좋지 않다고 생각되어,
승인 후 머지를 하려합니다.
mvc 미션 고생하셨습니다!

2022-09-30 02:11 UTC, merged

2022-09-30 02:26 UTC, dev-jiwonyang commented
앗 정완님 세심한 피드백과 칭찬 감사드립니다!!!
남은 미션들이 많아서... 다른 미션들을 허겁지겁 진행하느라 피드백 반영이 너무 늦어져버렸네요.... 🥲
정완님 댓글들 보고 힘이나서 ㅋㅋㅋ 남은 미션들도 재밌게 진행했어요~!
남겨주신 피드백들도 주말에 고민해보고 따로 구현해볼게요!
2단계 미션 동안 감사했고 최고의 리뷰어셨습니다 ㅎㅎ 👍