Step4
next-step/jwp-framework pull request #284
Opened 2022-10-24 07:18 UTC by pable91

안녕하세요.

mvc step4 리뷰 요청 보냅니다.

감잡기 너무 어려웠습니다ㅠㅠ

감사합니다.

2022-10-29 00:51 UTC, javajigi requested changes
이 단계가 예상보다 구현량도 많고 난이도도 높은 미션일 수 있는데 구현 잘 했네요. 💯 
전체적인 객체 설계는 잘 해서 특별히 피드백할 내용은 없지만 몇 가지 소소한 피드백 남겨 봅니다.

2022-10-29 00:51 UTC, javajigi commented on src/main/java/core/mvc/adapter/AnnotationHandlerAdapter.java
> +            e.printStackTrace();
exception을 무시해 버리면 예외 상황 처리를 하기 힘들지 않을까?

2022-10-29 00:51 UTC, javajigi commented on src/main/java/core/mvc/adapter/HandlerAdapter.java
> +public interface HandlerAdapter {
👍

2022-10-29 00:51 UTC, javajigi commented on src/main/java/core/mvc/adapter/SimpleControllerHandlerAdapter.java
> +public class SimpleControllerHandlerAdapter implements HandlerAdapter{
space convention 위반

2022-10-29 00:51 UTC, javajigi commented on src/main/java/core/mvc/resolver/PathVariableArgumentResolver.java
> +//        }
불필요한 주석은 삭제

2022-10-29 00:51 UTC, javajigi commented on src/main/java/core/mvc/resolver/PathVariableArgumentResolver.java
> +        return ResolverUtility.convertPrimitiveType(parameter.getParameterType(), object);
일급 콜렉션을 적용해 클래스를 분리하거나 메서드를 분리하는 것은 어떨까?

2022-10-29 00:51 UTC, javajigi commented on src/main/java/core/mvc/resolver/ResolverUtility.java
> +            return Float.parseFloat(object);
다수의 space convention 위반

2022-10-29 00:51 UTC, javajigi commented on src/main/java/core/mvc/resolver/PathVariableArgumentResolver.java
> +        String pathValue = parameter.getParameter().getAnnotation(PathVariable.class).value();
디미터 법칙 위반
값을 get하지 말고 parameter에 메시지를 보내면 어떨까?

```suggestion
        String pathValue = parameter.getAnnotaionValue(PathVariable.class);
```

2022-10-31 09:08 UTC, pable91 commented on src/main/java/core/mvc/resolver/PathVariableArgumentResolver.java
> +        return ResolverUtility.convertPrimitiveType(parameter.getParameterType(), object);
로직 분리가 제대로 안되어있고, 디미터법칙 적용도 잘 안되어있어서 제가 작업했는데도 코드 읽기가 힘들었습니다 ㅠㅠ

2022-11-01 09:10 UTC, pable91 commented
피드백 내용 + 리팩토링 할 부분 수정해서 재요청보냅니다.

jdbc 프로젝트 코드를 보니 일급콜렉션 관련 보완할 부분이 좀 보이더라구요 ㅎㅎ

2022-11-02 11:14 UTC, javajigi approved these changes
피드백 반영 잘 했네요. 💯 
4단계 미션이 정말 난이도가 높은 미션인데 포기하지 않고 끝까지 잘 마무리했네요.
다음 미션 진행하셔야죠?

2022-11-02 11:14 UTC, merged