[Step3] 3단계 - @MVC 구현(힌트)
next-step/jwp-framework pull request #46
Opened 2019-08-14 11:40 UTC by jaeyeonling

안녕하세요

3단계 구현 내용대로 구현해야 하는지 아니면 힌트로 참고만 하면 되는지 몰라 일단 구현하지 않았습니다. (ControllerScanner 등)

피드백 반영하니 따로 구현해야 하는 부분을 못찾겠어서 일단 리뷰요청 드립니다.

확인 후 부족한 부분 말씀 부탁드립니다.

감사합니다!

2019-08-15 09:56 UTC, byjo requested changes
2단계 피드백 내용 반영 및 리팩토링 확인하였습니다.
워낙 깔끔하게 잘 구현하셔서 크게 피드백 드릴 내용이 없네요. 💯💯💯
코멘트 드린 테스트를 추가해서 두 방식의 프레임워크가 잘 공존하는지 확인 후 마무리 하시면 되겠습니다.
고생 많으셨습니다!

2019-08-15 09:56 UTC, byjo commented on src/test/java/core/mvc/asis/DispatcherServletTest.java
> +class DispatcherServletTest {
이 테스트에 Adapter 리스트를 통해 두 방식의 프레임워크가 잘 동작하는지 여부를 확인하면 더 좋을 것 같습니다.

`LoginControllerTest`에서는 LoginController의 서비스 로직 자체에 대한 테스트(LoginController에 직접 요청을 했을 때 적합한 요청을 받는가의 여부 확인)를 하고,
`DispatcherServletTest`에서는 레거시/어노테이션 기반으로 맵핑된 handler를 요청했을 때 적합한 응답을 받는지에 대한 테스트를 해보면 어떨까요?

2019-08-15 09:56 UTC, byjo commented on src/main/java/core/mvc/ViewFactory.java
> +public final class ViewFactory {
ViewFactory가 추가되면서 요청 처리 흐름이 더 깔끔해졌네요👍

2019-08-17 16:50 UTC, jaeyeonling commented
안녕하세요

피드백 반영 조금 늦었습니다ㅠ

4단계 진행할 예정이오니 4단계도 좋은 리뷰 부탁드립니다!

2019-08-18 03:05 UTC, byjo approved these changes
피드백 반영해주신 사항 확인했습니다.
4단계 코드도 기대하겠습니다! 👍

2019-08-18 03:05 UTC, byjo commented on src/main/java/core/mvc/RedirectView.java
> +        return CACHE.computeIfAbsent(viewName, RedirectView::new);
View 재사용성을 높인 새로운 접근법 좋네요 👍

2019-08-18 03:06 UTC, merged