3단계 - @MVC 구현(힌트)
next-step/jwp-framework pull request #49
Opened 2019-08-14 16:59 UTC by changjun89

안녕하세요~ !
3단계 리뷰 요청드립니다.

3단계에서는 정확히 무엇을 해야할지 잘 몰라서
리뷰 해주신 부분과
3단계 힌트를 보고 약간 수정만 해보았습니다.

리뷰 부탁드립니다.
감사합니다.

2019-08-15 14:25 UTC, boorownie requested changes
요구사항 구현 및 피드백 반영 잘 해주셨습니다!
몇가지 코멘트 남겼는데요~ 
확인해보시고 참고해서 리팩토링 진행해주시면 좋을 것 같습니다!
궁금한 점 있으시면 언제든 DM 주세요~

2019-08-15 14:25 UTC, boorownie commented on src/main/java/core/mvc/asis/DispatcherServlet.java
>    protected void service(HttpServletRequest req, HttpServletResponse resp)
if/else 를 통해서 분기처리하고 있네요!
findController 메서드에서 req에 따라서 controller를 받아오고 있는데요
여기서 컨트롤러만 return 하기 보다는 컨트롤러를 수행하는 역할 까지 하면 
service에서 분기처리를 안해도 될 것 같은데요 한번 고민해보면 좋을 것 같습니다!

2019-08-15 14:25 UTC, probitanima11 commented on src/main/java/core/mvc/tobe/ControllerScanner.java
> +          } catch (InstantiationException e) {
Multi-Catch Exceptions을 사용해보면 어떨까요? :)
https://www.oracle.com/technetwork/articles/java/java7exceptions-486908.html

2019-08-15 14:25 UTC, probitanima11 commented on src/main/java/core/mvc/tobe/ControllerScanner.java
> +        .collect(Collectors.toMap(clazz -> clazz, clazz -> {
stream에서 한 파이프라인을 multi-line 보다는 single-line으로 구현하는게 가독성 좋을 것 같습니다 :)

2019-08-15 14:25 UTC, probitanima11 commented on src/main/java/core/mvc/asis/DispatcherServlet.java
>    private void move(String viewName, HttpServletRequest req, HttpServletResponse resp)
DispatcherServlet의 역할이라기 보다는 View의 역할로 보입니다!

2019-08-19 16:57 UTC, boorownie approved these changes
피드백 반영을 잘 해주셨네요 👍 
전체적인 흐름이 많이 개선된 것 같습니다!
흐름 이 외 추가적으로 피드백을 좀 더 남겼는데요
추가미션을 수행하신다면 해당 코멘트 참고해서 진행해주시면 좋을 것 같아요!
미션 수행하시느라 고생 많으셨습니다 👍

2019-08-19 16:57 UTC, boorownie commented on src/main/java/core/mvc/asis/DispatcherServlet.java
>      } catch (Exception e) {
controller의 execute메서드에 checked Exception인 Exception이 throw 되고 있는데요
이펙티브자바(2판) 규칙 59 "불필요한 점검지정 예외 사용은 피하라" 를 참고해보면 좋을 것 같아요 :)

[https://wickso.me/blog/effective-java-chapter-9-1#59-불필요한-점검지정-예외-사용은-피하라](https://wickso.me/blog/effective-java-chapter-9-1#59-%EB%B6%88%ED%95%84%EC%9A%94%ED%95%9C-%EC%A0%90%EA%B2%80%EC%A7%80%EC%A0%95-%EC%98%88%EC%99%B8-%EC%82%AC%EC%9A%A9%EC%9D%80-%ED%94%BC%ED%95%98%EB%9D%BC)
http://jtechies.blogspot.com/2012/07/blog-post_07.html

2019-08-19 16:57 UTC, boorownie commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +    HandlerAdaptor adaptor = findAdaptor(handler);
피드백반영 👍

2019-08-19 16:57 UTC, probitanima11 commented on src/main/java/core/mvc/tobe/ControllerScanner.java
> +    return null;
null 리턴 시 맵의 value에 null이 맵핑이 되는데요
이 경우 null 처리 등 고려해야 할 부분이 많아집니다.


clazz.newInstance() 를 실패할 경우 맵에 들어가지 않게 하는 방법을 고려해보는건 어떨까요?

2019-08-19 16:57 UTC, probitanima11 commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +    ControllerScanner controllerScanner = new ControllerScanner(basePackage.toString());
package 갯수 만큼 ControllerScanner를 생성하는 방법도 있지만
ControllerScanner에 package 배열을 넘겨서 처리하는 방법은 어떨까요?

2019-08-19 16:57 UTC, probitanima11 commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +  private void makeHandlerExecutionsAndFill(Object handler, List<Method> executionMethods) {
메서드 이름에서도 알 수 있듯 두가지 일을 하는 메서드로 보이는데요
handlerExecution을 만드는 메서드와 fill하는 부분을 리턴타입을 가지는 각각의 메서드로 분리해보면 어떨까요?
그리고 해당 메서드에 대해 단위테스트도 작성해보면 좋을 것 같습니다 ^^

2019-08-19 16:57 UTC, probitanima11 commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +        .forEach(controller ->
makeHandlerExecutionsAndFill 리팩토링 시 같이 리팩토링 하면 좋을 것 같습니다 :)
가능하면 메서드는 리턴타입을 두는게 좋은데 여러가지 장점 중 테스트 코드를 구현하는데 용이하다는 점이 있습니다.

2019-08-19 16:57 UTC, probitanima11 commented on src/main/java/core/mvc/asis/DispatcherServlet.java
> +      modelAndView.render(modelAndView.getModel(), req, resp);
modelAndView.render 메서드 호출 시 modelAndView.getModel()를 이용해서 파라미터를 넘겨줄 필요가 있을까요?

2019-08-22 15:00 UTC, gracefulBrown approved these changes

2019-08-22 15:01 UTC, boorownie approved these changes
리뷰반영 확인하였습니다!
끝까지 리뷰 반영 하시는 모습이 멋지네요 👍 👍
수고많으셨습니다~ 머지할게요!

2019-08-22 15:01 UTC, boorownie commented on src/main/java/core/mvc/asis/Controller.java
> +    String execute(HttpServletRequest req, HttpServletResponse resp);
👍

2019-08-22 15:01 UTC, merged