Step3 @MVC 구현
next-step/jwp-framework pull request #60
Opened 2019-08-18 10:13 UTC by phs1116

안녕하세요.
피드백 사항 반영 및 Leagcy, Annotation 기반 request mapping 추상화,
ControllerScanner 분리 반영하였습니다.
피드백 부탁드립니다.
감사합니다. :)

2019-08-19 13:57 UTC, boorownie requested changes
안녕하세요! 리뷰가 조금 늦었네요ㅠ
람다를 활용해서 HandlerExecutor와 HandlerExecution 구현한 부분이 인상깊네요 :)
몇가지 코멘트 남겼습니다! 고민해보시고 반영해보면 좋을 것 같아요~

2019-08-19 13:57 UTC, boorownie commented on src/main/java/core/mvc/tobe/AnnotationRequestMappingHandler.java
> +                handlerExecution.handle(request, response).render(request, response);
HandlerExecutor에서 handler 수행 이외에 rendering 작업을 수행하고 있습니다.
HandlerExecutor에서 view rendering 부분을 분리해보면 어떨까요?

2019-08-19 13:57 UTC, boorownie commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +    private List<HandlerKey> createHandlerKeys(RequestMapping requestMapping, String rootPath) {
AnnotationHandlerMapping과 RequestMethod의 관계가 맺어져있는데요
HandlerKey 부분을 리팩토링 하면 관계를 끊을 수 있을 것 같은데 고민해보면 좋을 것 같아요 :)

2019-08-21 17:55 UTC, phs1116 commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +    private List<HandlerKey> createHandlerKeys(RequestMapping requestMapping, String rootPath) {
말씀하신 바를 제대로 이해한건지 잘 모르겠습니다만,
HandlerKey 리스트를 생성하는 부분을 HandlerKey의 static factory method로 생성했습니다.

2019-08-21 17:56 UTC, phs1116 commented on src/main/java/core/mvc/tobe/AnnotationRequestMappingHandler.java
> +                handlerExecution.handle(request, response).render(request, response);
ModelAndView를 리턴하도록 수정하여 디스패쳐 서블릿에서 렌더하도록 수정했습니다.

2019-08-23 04:58 UTC, boorownie approved these changes
피드백 반영 및 고민 해보시느라 고생 많으셨습니다 💯 
구현을 워낙 잘 해주셔서 특별히 코멘트 남겨드릴 부분이 많이 없네요 ^^;;
Advanced 미션 구현도 기대해 볼게요 :)
만약 이번 단계에서 마무리하고 싶으면 DM 보내주시구요
머지할게요~

2019-08-23 04:58 UTC, probitanima11 commented on src/main/java/core/mvc/tobe/AnnotationHandlerMapping.java
> +        return handlerExecutions.get(new HandlerKey(requestUri, rm));
특별히 중요한 내용은 아니고 
이 부분에서 request를 HandlerKey의 인자로 만들면 
AnnotationHandlerMapping과 RequestMethod의 연관관계를 끊을 수 있을 것 같아서 코멘트 드렸었습니다 ^^;;

2019-08-23 04:58 UTC, merged